### ISSUE TITLE
Relabel RECON-ALL: Freesurfer v5.3.0 gears

### ISSUE THREAD

**Issue by elisapoquette** [flywheel-apps/reconall-demo#1]
Should read "Freesurfer: RECON-ALL v5.3.0(DEMO)"

Going forward, all FreeSurfer, FSL, SPM Gears should follow this labeling convention (Library/Software Package: Name) when possible.

**Comment by elisapoquette** [comment]
@lmperry Can you update this manifest for this Gear? I think this is the only Gear I noticed not using the preferred nomenclature. Also, not sure how to enforce this going forward. Ideas?

**Comment by lmperry** [comment]
Closed via  a57b245
